### PR TITLE
Adding database section, Jolene's edits

### PR DESCRIPTION
**Pull request by aejolene**

### CODE REVIEW

**Comment by aejolene** [comment]
I didn't change the names of all the sections. Created a new file called 2.1.1 but that should probably be 2.2 and shift everything?

**Comment by shawngraham** [comment]
i changed 2.2 to be your databases and made the openrefine to be just an exercise within that section

**Comment by aejolene** [comment]
Sounds good!

**Comment by aejolene** [comment]
I kind of feel like cleaning data still needs a section. What do you think of this structure? The openrefine exercise could go in there?

2. Making Data useful
    Making data Sensible
    Making data Durable
  2.1 Designing Data collection
  2.2 Cleaning data (new)
  2.3 Databases
  2.4 Digital libraries
  2.5 command line apis

**Comment by shawngraham** [comment]
Sounds good. We don't have to worry about the numbering, as the system will take care of that automagically. Just give it the appropriate level heading and we're good to go. I have a section in workbook.craftingdigitalhistory.ca that could be repurposed re data cleaning? Unfortunately, it's all about a network graph from correspondence. Not overly archaeological.

On a related note, I'm building a notebook that shows how to ingest a bunch of data files into a single database. Another one showing some basic SQL queries. Useful?

**Pull request merged**
